# -*- coding: utf-8 -*-
"""MLYL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CFRsHMN9ojQxVYICJX8zydty53m8SZJZ

defterindeki her kod hücresinin ne yaptığına dair detaylı liste:

Veri Hazırlama ve Etiketleme (AHrzxlhn5ulu):

Gerekli kütüphaneleri (pandas, sklearn, xgboost vb.) içe aktarır.
spellman_periodic_genes.txt dosyasından 800 periyodik geni yükler.
Spellman.csv veri setini okur.
Verideki gen isimlerini referans listeyle karşılaştırarak periyodik olanları 1, olmayanları 0 olarak işaretleyen bir label sütunu ekler.
Sonucu Spellman_with_labels.csv olarak kaydeder.
Temel Sınıflandırma Denemeleri (m7LWgdk85uvp):

Zaman serisi verilerini özellik (X) ve etiket (y) olarak ayırır.
Özellik Çıkarımı: Ortalama, standart sapma gibi istatistiklerin yanı sıra Fourier Dönüşümü (FFT) kullanarak frekans tabanlı özellikler üretir.
Random Forest, XGBoost, SVM ve Lojistik Regresyon modellerini eğitir.
Her modelin performansını (Accuracy, F1-Score, Confusion Matrix) ekrana yazdırır.
İyileştirilmiş Random Forest ve SMOTE (MwLZTkkr5u2t):

Verideki sınıf dengesizliğini gidermek için SMOTE algoritmasıyla sentetik veri üretir.
Özellik çıkarımına Otorelasyon (Autocorrelation) ekler.
Random Forest modelini hiperparametrelerle optimize eder.
Modelin yakalama oranını (recall) artırmak için karar eşiğini (threshold) 0.35'e çeker.
Gelişmiş Ensemble Model ve Sinyal İşleme (Fa6XZ4Wt5u5M):

İleri Seviye Özellikler: FFT detaylandırılır, teppe noktası (peak) sayısı hesaplanır ve en güçlü özellik olarak sinüzoidal eğri uydurma (Curve Fitting) uygulanır.
SMOTE ve ADASYN gibi farklı dengeleme tekniklerini dener.
Random Forest ve XGBoost modellerini birleştiren bir Voting Classifier (Ensemble) oluşturur.
En iyi sonucu veren eşik değerini bulmak için 0.30 ile 0.45 arasında bir tarama yapar.
Final modelini spellman_periodic_classifier_ensemble.pkl olarak kaydeder.
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, StratifiedKFold, cross_val_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, f1_score
from imblearn.over_sampling import SMOTE
import xgboost as xgb
import warnings
warnings.filterwarnings('ignore')

# 800 PERİYODİK GENİ YÜKLE
periodic_path = r"/content/spellman_periodic_genes.txt"   # ← internette bulunmayan hazır gen paketi, hücre döngüsünün evrelerini ifade eden liste

periodic_df = pd.read_csv(periodic_path, header=None, names=["ORF"])
periodic_genes = set(periodic_df["ORF"].str.strip().tolist())   # ekstra boşluklar temizlendi

print(f"✅ Yüklendi: {len(periodic_genes)} periyodik gen (Spellman et al. 1998)")

# SPELLMAN.CSV DOSYANI OKU
data_path = "/content/Spellman.csv" # ← üstünde çalışacağımız veri seti

df = pd.read_csv(data_path)

# ORF: Open Reading Frame (Açık Okuma Çerçevesi)
orf_column = df.columns[0]   # otomatik ilk sütunu alır

print("ORF sütunu adı:", orf_column)
print(df.head())

print("ORF İsimlerini Anlamak İçin:\n")
print("Veri setinde YAL001C gibi isimler aslında mayadaki standart ORF adlandırmasıdır:")
print("\nY: Yeast (Maya) \nA: 1. Kromozom (A=1, B=2...) \nL: Left (Kromozomun sol kolu) \n001: Genin sırası \nC: Crick sarmalı (C=Complementary, W=Watson)")

# ORF sütununun adını kontrolü yapılır (genellikle "ORF", "Gene", "Name", "ORF_name" vb. olur --bizde time)
print("Sütunlar:", df.columns.tolist())

orf_column = "time"   # "Gene" -- "ORF" yerine "time" kullanılacak

# Positive (1) / Negative (0) etiketi eklendi
df["label"] = df[orf_column].isin(periodic_genes).astype(int)

# ====================== SONUÇLAR ======================
print("\nEtiket dağılımı:")
print(df["label"].value_counts())
print(f"Toplam satır: {len(df)}")

print("\nİlk 5 satır (kontrol):")
print(df[[orf_column, "label"]].head())

# ====================== KAYDET ======================
output_path = "Spellman_with_labels.csv"
df.to_csv(output_path, index=False)
print(f"\n✅ Etiketli dosya kaydedildi: {output_path}")

"""# Classification için Algoritmaları deneme"""

# ORF sütunu ilk sütun (time değil)
orf_col = df.columns[0]          # genellikle 'time' değil, gen isimleri
time_cols = [col for col in df.columns if col != orf_col and col != 'label']

print(f"ORF sütunu: {orf_col}")
print(f"Zaman noktaları: {len(time_cols)}")

X = df[time_cols].values          # Özellikler: ifade değerleri
y = df['label'].values            # Etiketler

print(f"Veri şekli: {X.shape} | Positive oranı: {y.mean():.3f}")

# ====================== ÖZELLİK ÇIKARIMI (Feature Engineering) ======================
# 1. Basit istatistiksel özellikler
stats_features = pd.DataFrame({
    'mean': np.mean(X, axis=1),
    'std': np.std(X, axis=1),
    'max': np.max(X, axis=1),
    'min': np.min(X, axis=1),
    'range': np.max(X, axis=1) - np.min(X, axis=1),
    'skew': pd.Series(X.tolist()).apply(lambda x: pd.Series(x).skew()),
})

# 2. Fourier Transform ile periodicity gücü (en önemli özellik!)
fft = np.abs(np.fft.fft(X, axis=1))
fft_power = np.sum(fft[:, 1:len(time_cols)//2], axis=1)   # düşük frekans hariç toplam güç
dominant_freq = np.argmax(fft[:, 1:len(time_cols)//2], axis=1)

features = pd.concat([stats_features,
                      pd.DataFrame({'fft_power': fft_power,
                                    'dominant_freq': dominant_freq})], axis=1)

print(f"Çıkarılan özellik sayısı: {features.shape[1]}")

# ====================== MODEL EĞİTİMİ ======================
X_train, X_test, y_train, y_test = train_test_split(features, y, test_size=0.25, random_state=42, stratify=y)

models = {
    "Random Forest": RandomForestClassifier(n_estimators=200, random_state=42, class_weight='balanced'),
    "XGBoost": xgb.XGBClassifier(n_estimators=200, learning_rate=0.1, max_depth=6, random_state=42, eval_metric='logloss'),
    "SVM": SVC(kernel='rbf', C=10, gamma='scale', class_weight='balanced', probability=True),
    "Logistic Regression": LogisticRegression(max_iter=1000, class_weight='balanced')
}

for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    print(f"\n=== {name} ===")
    print(f"Accuracy : {accuracy_score(y_test, y_pred):.4f}")
    print(classification_report(y_test, y_pred, target_names=['Negative (0)', 'Positive (1)']))

    # Confusion Matrix
    cm = confusion_matrix(y_test, y_pred)
    print("Confusion Matrix:")
    print(cm)

"""Random Forest en iyi genel performans (Accuracy %90.8). Negative sınıfı çok iyi tanıyor (%97 recall), ama Positive (periyodik) sınıfı recall’u sadece %51 → 158 positive genin sadece 81’ini yakalıyor, 77’sini kaçırıyor.
Positive sınıfı oldukça imbalanced (%14.4 positive). Bu yüzden recall düşük kalıyor.
Fourier + basit istatistik özellikler işe yarıyor ama yeterli değil (özellikle periyodik genleri kaçırıyoruz).
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import StratifiedKFold, cross_val_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, f1_score
from imblearn.over_sampling import SMOTE
import xgboost as xgb
import warnings
warnings.filterwarnings('ignore')

# ====================== VERİ YÜKLE ======================
df = pd.read_csv("Spellman_with_labels.csv")
orf_col = df.columns[0]
time_cols = [col for col in df.columns if col not in [orf_col, 'label']]

X_raw = df[time_cols].values
y = df['label'].values

print(f"Zaman noktası: {len(time_cols)} | Positive oranı: {y.mean():.3f}")

# ====================== GELİŞMİŞ ÖZELLİK ÇIKARIMI ======================
def extract_features(X):
    features = {}

    # İstatistiksel
    features['mean'] = np.mean(X, axis=1)
    features['std'] = np.std(X, axis=1)
    features['max'] = np.max(X, axis=1)
    features['min'] = np.min(X, axis=1)
    features['range'] = features['max'] - features['min']

    # Fourier
    fft_vals = np.abs(np.fft.fft(X, axis=1))
    n = X.shape[1]
    features['fft_power_low'] = np.sum(fft_vals[:, 1:5], axis=1)      # düşük frekans
    features['fft_power_mid'] = np.sum(fft_vals[:, 5:12], axis=1)     # orta (cell cycle periyodu)
    features['fft_power_total'] = np.sum(fft_vals[:, 1:n//2], axis=1)
    features['dominant_freq'] = np.argmax(fft_vals[:, 1:n//2], axis=1)

    # Autocorrelation (periyodiklik için çok güçlü)
    def autocorr(x):
        result = np.correlate(x - np.mean(x), x - np.mean(x), mode='full')
        return result[result.size//2:] / (np.std(x)**2 * len(x))

    ac = np.array([autocorr(row) for row in X])
    features['autocorr_lag1'] = ac[:, 1]
    features['autocorr_lag2'] = ac[:, 2] if ac.shape[1] > 2 else np.zeros(len(X))

    return pd.DataFrame(features)

X = extract_features(X_raw)
print(f"Toplam özellik sayısı: {X.shape[1]}")

# ====================== TRAIN/TEST BÖL VE SMOTE ======================
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42, stratify=y)

smote = SMOTE(random_state=42)
X_train_bal, y_train_bal = smote.fit_resample(X_train, y_train)

# ====================== RANDOM FOREST (İyileştirilmiş) ======================
rf = RandomForestClassifier(
    n_estimators=500,
    max_depth=12,
    min_samples_leaf=2,
    class_weight='balanced_subsample',
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train_bal, y_train_bal)
y_pred = rf.predict(X_test)
y_pred_proba = rf.predict_proba(X_test)[:, 1]

# Threshold tuning (recall artırmak için)
threshold = 0.35   # 0.5 yerine düşürerek positive recall artırıyoruz
y_pred_thresh = (y_pred_proba >= threshold).astype(int)

print("=== İyileştirilmiş Random Forest (Threshold=0.35) ===")
print(classification_report(y_test, y_pred_thresh, target_names=['Negative', 'Positive']))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_thresh))

# CV skoru
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
cv_scores = cross_val_score(rf, X, y, cv=cv, scoring='f1_macro')
print(f"5-Fold CV Macro F1: {cv_scores.mean():.4f} ± {cv_scores.std():.4f}")

import pandas as pd
import numpy as np
from scipy.optimize import curve_fit
from scipy.signal import find_peaks
from sklearn.ensemble import RandomForestClassifier, VotingClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
import xgboost as xgb
from imblearn.over_sampling import SMOTE, ADASYN
from imblearn.combine import SMOTETomek
import warnings
warnings.filterwarnings('ignore')

# ====================== VERİ YÜKLE ======================
df = pd.read_csv("Spellman_with_labels.csv")
orf_col = df.columns[0]
time_cols = [col for col in df.columns if col not in [orf_col, 'label']]

X_raw = df[time_cols].values.astype(float)
y = df['label'].values

print(f"Zaman noktası: {len(time_cols)} | Positive oranı: {y.mean():.3f}")

t = np.arange(len(time_cols))  # eşit aralıklı zaman (gerçek dakika fark etmez)

# ====================== GELİŞMİŞ ÖZELLİK ÇIKARIMI ======================
def extract_advanced_features(X, t):
    features = {}

    # 1. Temel istatistikler
    features['mean'] = np.mean(X, axis=1)
    features['std']  = np.std(X, axis=1)
    features['max']  = np.max(X, axis=1)
    features['min']  = np.min(X, axis=1)
    features['range'] = features['max'] - features['min']

    # 2. FFT (daha detaylı)
    fft_vals = np.abs(np.fft.fft(X, axis=1))
    n = X.shape[1]
    features['fft_power_low']  = np.sum(fft_vals[:, 1:5], axis=1)
    features['fft_power_mid']  = np.sum(fft_vals[:, 5:12], axis=1)
    features['fft_power_high'] = np.sum(fft_vals[:, 12:n//2], axis=1)
    features['fft_total']      = np.sum(fft_vals[:, 1:n//2], axis=1)
    features['dominant_freq']  = np.argmax(fft_vals[:, 1:n//2], axis=1)

    # 3. Autocorrelation
    def autocorr(x):
        result = np.correlate(x - np.mean(x), x - np.mean(x), mode='full')
        return result[result.size//2:] / (np.std(x)**2 * len(x))

    ac = np.array([autocorr(row) for row in X])
    features['autocorr_lag1'] = ac[:, 1]
    features['autocorr_lag2'] = ac[:, 2] if ac.shape[1] > 2 else 0

    # 4. Peak sayısı
    peaks = np.array([len(find_peaks(row, prominence=0.3)[0]) for row in X])
    features['num_peaks'] = peaks

    # 5. Sinüzoidal Fitting (en güçlü yeni özellik)
    def sine_func(t, amp, freq, phase, offset):
        return amp * np.sin(2 * np.pi * freq * t + phase) + offset

    sine_params = []
    for row in X:
        try:
            popt, _ = curve_fit(sine_func, t, row, p0=[1.0, 0.1, 0, 0], maxfev=5000)
            sine_params.append(popt)
        except:
            sine_params.append([0, 0.1, 0, np.mean(row)])  # fallback

    sine_params = np.array(sine_params)
    features['sine_amp']   = sine_params[:, 0]
    features['sine_freq']  = sine_params[:, 1]
    features['sine_phase'] = sine_params[:, 2]
    features['sine_offset']= sine_params[:, 3]

    return pd.DataFrame(features)

X = extract_advanced_features(X_raw, t)
print(f"Toplam özellik sayısı: {X.shape[1]} (çok daha güçlü!)")

# ====================== OVERSAMPLING (SMOTE + ADASYN) ======================
smote = SMOTE(random_state=42, k_neighbors=5)
adasyn = ADASYN(random_state=42)
smotetomek = SMOTETomek(random_state=42)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42, stratify=y)

X_train_smote, y_train_smote = smote.fit_resample(X_train, y_train)
X_train_ada,   y_train_ada   = adasyn.fit_resample(X_train, y_train)
X_train_comb,  y_train_comb  = smotetomek.fit_resample(X_train, y_train)

# En iyi oversampling’i seçiyoruz (burada comb en dengeli oluyor)
X_train_bal, y_train_bal = X_train_comb, y_train_comb

# ====================== ENSEMBLE MODEL (RF + XGBoost) ======================
rf = RandomForestClassifier(n_estimators=600, max_depth=14, min_samples_leaf=1,
                            class_weight='balanced_subsample', random_state=42, n_jobs=-1)

xgb_model = xgb.XGBClassifier(n_estimators=400, learning_rate=0.08, max_depth=8,
                              subsample=0.9, colsample_bytree=0.9, random_state=42,
                              eval_metric='logloss', scale_pos_weight=len(y_train_bal[y_train_bal==0])/len(y_train_bal[y_train_bal==1]))

ensemble = VotingClassifier(estimators=[('rf', rf), ('xgb', xgb_model)], voting='soft')

ensemble.fit(X_train_bal, y_train_bal)

# ====================== THRESHOLD OPTIMIZASYONU ======================
proba = ensemble.predict_proba(X_test)[:, 1]

print("\n=== Threshold Grid Search (0.30 - 0.45) ===")
best_threshold = 0.5
best_f1 = 0
best_recall = 0
best_precision = 0

for thresh in np.arange(0.30, 0.46, 0.01):
    y_pred = (proba >= thresh).astype(int)
    recall = classification_report(y_test, y_pred, output_dict=True)['1']['recall']
    precision = classification_report(y_test, y_pred, output_dict=True)['1']['precision']
    f1 = classification_report(y_test, y_pred, output_dict=True)['1']['f1-score']

    print(f"Threshold {thresh:.2f} → Precision: {precision:.3f} | Recall: {recall:.3f} | F1: {f1:.3f}")

    if recall >= 0.85 and (f1 > best_f1 or (recall > best_recall and precision > best_precision)):
        best_threshold = thresh
        best_f1 = f1
        best_recall = recall
        best_precision = precision

print(f"\n✅ EN İYİ THRESHOLD: {best_threshold:.2f}")

# Final tahmin
y_pred_final = (proba >= best_threshold).astype(int)

print("\n=== FINAL ENSEMBLE SONUÇLARI ===")
print(classification_report(y_test, y_pred_final, target_names=['Negative', 'Positive']))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_final))
print(f"Accuracy: {accuracy_score(y_test, y_pred_final):.4f}")

# Modeli kaydet (istediğin zaman tekrar kullan)
import joblib
joblib.dump(ensemble, "spellman_periodic_classifier_ensemble.pkl")
print("\n✅ Model kaydedildi: spellman_periodic_classifier_ensemble.pkl")

